### ISSUE TITLE
An error occurred while scanning the remote server.

### ISSUE THREAD

**Issue by Malpractis** [ipsingh06/seedsync#12]
Hey I think I'm getting ssh timeouts. I've tried adding ServerAliveInterval 30 to /etc/ssh/ssh_config. But I'm assuming you might not be using the default ssh service as I can't find any way to restart the service.

````
2018/06/25 13:30:58 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Timed out
Traceback (most recent call last):
File "site-packages/pexpect/expect.py", line 99, in expect_loop
File "site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/ssh/sshcp.py", line 79, in __run_command
File "site-packages/pexpect/spawnbase.py", line 321, in expect
File "site-packages/pexpect/spawnbase.py", line 345, in expect_list
File "site-packages/pexpect/expect.py", line 107, in expect_loop
File "site-packages/pexpect/expect.py", line 70, in timeout
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f516c1f00b8>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-p', '57457', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', 'enigma28@185.56.20.34', "'/downloads/scanfs/scanfs' '/downloads/tv-complete'"]
buffer (last 100 chars): b''
before (last 100 chars): b''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 608
child_fd: 91
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("b'password: '")
1: re.compile("b'lost connection'")
2: re.compile("b'Could not resolve hostname'")
2018/06/25 13:30:58 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Command output before: b''
2018/06/25 13:30:58 - ERROR - RemoteScanner.RemoteScanner - Caught an SshError
Traceback (most recent call last):
File "site-packages/pexpect/expect.py", line 99, in expect_loop
File "site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/ssh/sshcp.py", line 79, in __run_command
File "site-packages/pexpect/spawnbase.py", line 321, in expect
File "site-packages/pexpect/spawnbase.py", line 345, in expect_list
File "site-packages/pexpect/expect.py", line 107, in expect_loop
File "site-packages/pexpect/expect.py", line 70, in timeout
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f516c1f00b8>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-p', '57457', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', 'enigma28@185.56.20.34', "'/downloads/scanfs/scanfs' '/downloads/tv-complete'"]
buffer (last 100 chars): b''
before (last 100 chars): b''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 608
child_fd: 91
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("b'password: '")
1: re.compile("b'lost connection'")
2: re.compile("b'Could not resolve hostname'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/controller/scan/remote_scanner.py", line 60, in scan
File "python/ssh/sshcp.py", line 143, in shell
File "python/ssh/sshcp.py", line 102, in __run_command
ssh.sshcp.SshcpError: Timed out
2018/06/25 13:30:58 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "python/common/job.py", line 44, in run
File "python/controller/controller_job.py", line 29, in execute
File "python/controller/controller.py", line 199, in process
File "python/controller/controller.py", line 523, in __propagate_exceptions
File "python/common/app_process.py", line 124, in propagate_exception
File "python/common/app_process.py", line 30, in re_raise
File "python/common/app_process.py", line 87, in run
File "python/controller/scan/scanner_process.py", line 71, in run_loop
File "python/controller/scan/remote_scanner.py", line 71, in scan
common.error.AppError: An error occurred while scanning the remote server.
2018/06/25 13:30:58 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "python/seedsync.py", line 162, in run
File "python/common/job.py", line 77, in propagate_exception
File "python/common/job.py", line 44, in run
File "python/controller/controller_job.py", line 29, in execute
File "python/controller/controller.py", line 199, in process
File "python/controller/controller.py", line 523, in __propagate_exceptions
File "python/common/app_process.py", line 124, in propagate_exception
File "python/common/app_process.py", line 30, in re_raise
File "python/common/app_process.py", line 87, in run
File "python/controller/scan/scanner_process.py", line 71, in run_loop
File "python/controller/scan/remote_scanner.py", line 71, in scan
common.error.AppError: An error occurred while scanning the remote server.
```
Any help would be most appreciated.

I'm running SeedSync in a docker container.

**Comment by nitrobass24** [comment]
I am also getting similar timeout issues, several times a day. 

`2018/09/07 16:59:44 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Timed out
Traceback (most recent call last):
File "site-packages/pexpect/expect.py", line 99, in expect_loop
File "site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/ssh/sshcp.py", line 79, in __run_command
File "site-packages/pexpect/spawnbase.py", line 321, in expect
File "site-packages/pexpect/spawnbase.py", line 345, in expect_list
File "site-packages/pexpect/expect.py", line 107, in expect_loop
File "site-packages/pexpect/expect.py", line 70, in timeout
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f59446bd710>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', 'nitrobass24@peak.seedhost.eu', "'/home31/nitrobass24/seedsync/scanfs' '/home31/nitrobass24/downloads/completed'"]
buffer (last 100 chars): b''
before (last 100 chars): b''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 2807
child_fd: 64
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("b'password: '")
1: re.compile("b'lost connection'")
2: re.compile("b'Could not resolve hostname'")
2018/09/07 16:59:44 - ERROR - RemoteScanner.RemoteScanner.Sshcp - Command output before: b''
2018/09/07 16:59:44 - ERROR - RemoteScanner.RemoteScanner - Caught an SshError
Traceback (most recent call last):
File "site-packages/pexpect/expect.py", line 99, in expect_loop
File "site-packages/pexpect/pty_spawn.py", line 462, in read_nonblocking
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/ssh/sshcp.py", line 79, in __run_command
File "site-packages/pexpect/spawnbase.py", line 321, in expect
File "site-packages/pexpect/spawnbase.py", line 345, in expect_list
File "site-packages/pexpect/expect.py", line 107, in expect_loop
File "site-packages/pexpect/expect.py", line 70, in timeout
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f59446bd710>
command: /usr/bin/ssh
args: ['/usr/bin/ssh', '-p', '22', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'LogLevel=error', '-o', 'PubkeyAuthentication=no', 'nitrobass24@peak.seedhost.eu', "'/home31/nitrobass24/seedsync/scanfs' '/home31/nitrobass24/downloads/completed'"]
buffer (last 100 chars): b''
before (last 100 chars): b''
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 2807
child_fd: 64
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
0: re.compile("b'password: '")
1: re.compile("b'lost connection'")
2: re.compile("b'Could not resolve hostname'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "python/controller/scan/remote_scanner.py", line 60, in scan
File "python/ssh/sshcp.py", line 143, in shell
File "python/ssh/sshcp.py", line 102, in __run_command
ssh.sshcp.SshcpError: Timed out
2018/09/07 16:59:44 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "python/common/job.py", line 44, in run
File "python/controller/controller_job.py", line 29, in execute
File "python/controller/controller.py", line 199, in process
File "python/controller/controller.py", line 523, in __propagate_exceptions
File "python/common/app_process.py", line 124, in propagate_exception
File "python/common/app_process.py", line 30, in re_raise
File "python/common/app_process.py", line 87, in run
File "python/controller/scan/scanner_process.py", line 71, in run_loop
File "python/controller/scan/remote_scanner.py", line 71, in scan
common.error.AppError: An error occurred while scanning the remote server.
2018/09/07 16:59:44 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "python/seedsync.py", line 162, in run
File "python/common/job.py", line 77, in propagate_exception
File "python/common/job.py", line 44, in run
File "python/controller/controller_job.py", line 29, in execute
File "python/controller/controller.py", line 199, in process
File "python/controller/controller.py", line 523, in __propagate_exceptions
File "python/common/app_process.py", line 124, in propagate_exception
File "python/common/app_process.py", line 30, in re_raise
File "python/common/app_process.py", line 87, in run
File "python/controller/scan/scanner_process.py", line 71, in run_loop
File "python/controller/scan/remote_scanner.py", line 71, in scan
common.error.AppError: An error occurred while scanning the remote server.`

**Comment by ipsingh06** [comment]
Please try the latest version and see if it fixes your issue.

The ServerAliveInterval should have no effect on SeedSync because the ssh connections are short lived. If you are experiencing timeout issues then it just means that your remote server is experiencing downtime.
