### ISSUE TITLE
cron permission issue

### ISSUE THREAD

**Issue by gamera2** [ipsingh06/seedsync#127]
G'day, hope it's okay to ask this here. I've set up SSH to my remote server and it seems to have got as far as installing scanfs, but now it's giving me a permission error with cron. I've got seedsync set up as a container in Unraid.

`2022/11/22 16:29:28 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 164, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 68, in scan
raise ScannerError(
controller.scan.scanner_process.ScannerError: An error occurred while scanning the remote server: 'Traceback (most recent call last):
File "scan_fs.py", line 27, in <module>
File "system/scanner.py", line 84, in scan
File "system/scanner.py", line 187, in __create_children
File "system/scanner.py", line 128, in __create_system_file
File "system/scanner.py", line 187, in __create_children
File "system/scanner.py", line 128, in __create_system_file
File "system/scanner.py", line 174, in __create_children
PermissionError: [Errno 13] Permission denied: '/home/user/.config/cron'
[47151] Failed to execute script scan_fs'.`

These are the permissions for cron:
`myuser@myuser-seedbox:~/.config$ ls -la
total 16
drwxr-xr-x.  9 myuser   myuser   4096 Jan 21  2021 .
drwxr-x---. 14 myuser   myuser   4096 Nov 22 07:36 ..
drwx------   2 myuser   myuser     48 Aug 24  2018 configstore
drwx-wx--T   2 root     crontab    10 Jul 13  2017 cron`

I don't know if I should be messing with the cron permissions, or is there a way for seedsync to add a cron job as a user instead ?

**Comment by quadcom** [comment]
Normally, scanfs issues are down to the permissions with the target on the Seedbox you are trying to store scanfs in.

Some seedboxes allow you to write in the root folder of your instance, some don't. If you SSH in and can create a "scan" folder in the root, target that for scanfs in the settings.

If you can't there's most likely a "files" folder where all the seeds are DL'd to. Create the "scan" folder there and target the scanfs in settings to that folder.

I have never touched any cron config on any seedbox host I have ever used.

**Comment by gamera2** [comment]
Hi, thanks for your reply. I looked a little closer and it was creating the error while it was trying to scan the remote file system. And it would hit a directory owned by root and fail. So I fixed the Server Directory setting so it was only trying to scan the directory where my downloads were instead. Looks to be working now. Thanks for your help.
