### ISSUE TITLE
Cant connect to a Mac Mini Share

### ISSUE THREAD

**Issue by NSBSD-InfoTech** [ipsingh06/seedsync#17]
2018/10/19 17:13:50 - ERROR - RemoteScanner.RemoteScanner - Caught an SshError
Traceback (most recent call last): File "python/controller/scan/remote_scanner.py", line 60, in scan File "python/ssh/sshcp.py", line 143, in shell File "python/ssh/sshcp.py", line 109, in __run_command ssh.sshcp.SshcpError: bash: /tmp/scanfs: cannot execute binary file
 
2018/10/19 17:13:51 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last): File "python/common/job.py", line 44, in run File "python/controller/controller_job.py", line 29, in execute File "python/controller/controller.py", line 199, in process File "python/controller/controller.py", line 523, in __propagate_exceptions File "python/common/app_process.py", line 124, in propagate_exception File "python/common/app_process.py", line 30, in re_raise File "python/common/app_process.py", line 87, in run File "python/controller/scan/scanner_process.py", line 71, in run_loop File "python/controller/scan/remote_scanner.py", line 71, in scan common.error.AppError: An error occurred while scanning the remote server.
2018/10/19 17:13:51 - ERROR - seedsync - Caught exception
Traceback (most recent call last): File "python/seedsync.py", line 162, in run File "python/common/job.py", line 77, in propagate_exception File "python/common/job.py", line 44, in run File "python/controller/controller_job.py", line 29, in execute File "python/controller/controller.py", line 199, in process File "python/controller/controller.py", line 523, in __propagate_exceptions File "python/common/app_process.py", line 124, in propagate_exception File "python/common/app_process.py", line 30, in re_raise File "python/common/app_process.py", line 87, in run File "python/controller/scan/scanner_process.py", line 71, in run_loop File "python/controller/scan/remote_scanner.py", line 71, in scan common.error.AppError: An error occurred while scanning the remote server.
2018/10/19 17:13:52 - INFO - seedsync.Controller - Exited controller
2018/10/19 17:18:40 - INFO - seedsync.ServerActionHandler - Received a restart action
2018/10/19 17:18:40 - INFO - seedsync - Exiting Seedsync
Lost connection to service

**Comment by ipsingh06** [comment]
At this time a Mac remote server is not supported, sorry. It requires compiling the remote scanfs executable for a Mac architecture.
