### ISSUE TITLE
An error occurred while scanning the remote server

### ISSUE THREAD

**Issue by seannymurrs** [ipsingh06/seedsync#18]
I get the following errors in my logs.

```
2018/12/18 08:57:43 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Return code: 126
2018/12/18 08:57:43 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command took 1.751s
2018/12/18 08:57:43 - ERROR - RemoteScanner.RemoteScanner - Caught an SshError
Traceback (most recent call last): File "python/controller/scan/remote_scanner.py", line 60, in scan File "python/ssh/sshcp.py", line 143, in shell File "python/ssh/sshcp.py", line 109, in __run_command ssh.sshcp.SshcpError: 
 bash: /home/user/tmp/scanfs: Is a directory
 
2018/12/18 08:57:43 - DEBUG - RemoteScanner - Process caught an exception
2018/12/18 08:57:44 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last): File "python/common/job.py", line 44, in run File "python/controller/controller_job.py", line 29, in execute File "python/controller/controller.py", line 199, in process File "python/controller/controller.py", line 523, in __propagate_exceptions File "python/common/app_process.py", line 124, in propagate_exception File "python/common/app_process.py", line 30, in re_raise File "python/common/app_process.py", line 87, in run File "python/controller/scan/scanner_process.py", line 71, in run_loop File "python/controller/scan/remote_scanner.py", line 71, in scan common.error.AppError: An error occurred while scanning the remote server.
2018/12/18 08:57:44 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob
2018/12/18 08:57:44 - DEBUG - seedsync.Controller - Exiting controller
2018/12/18 08:57:44 - ERROR - seedsync - Caught exception
Traceback (most recent call last): File "python/seedsync.py", line 162, in run File "python/common/job.py", line 77, in propagate_exception File "python/common/job.py", line 44, in run File "python/controller/controller_job.py", line 29, in execute File "python/controller/controller.py", line 199, in process File "python/controller/controller.py", line 523, in __propagate_exceptions File "python/common/app_process.py", line 124, in propagate_exception File "python/common/app_process.py", line 30, in re_raise File "python/common/app_process.py", line 87, in run File "python/controller/scan/scanner_process.py", line 71, in run_loop File "python/controller/scan/remote_scanner.py", line 71, in scan common.error.AppError: An error occurred while scanning the remote server.
2018/12/18 08:57:45 - DEBUG - ActiveScanner - Process received terminate flag
2018/12/18 08:57:45 - DEBUG - ActiveScanner - Exiting process
2018/12/18 08:57:46 - DEBUG - ExtractProcess - Process received terminate flag
2018/12/18 08:57:46 - DEBUG - seedsync.Controller.MPLogger - Stopped listener thread
2018/12/18 08:57:46 - INFO - seedsync.Controller - Exited controller
2018/12/18 08:57:46 - DEBUG - seedsync.ControllerJob - Finished cleanup for ControllerJob
2018/12/18 08:57:46 - DEBUG - seedsync.ControllerJob - Thread ControllerJob stopped
2018/12/18 08:57:58 - DEBUG - seedsync - Persisting states to file
```

**Comment by seannymurrs** [comment]
I figured out the issue. I changed the script directory from /home/user/tmp/scanfs to /home/user/scanfs

**Comment by ipsingh06** [comment]
Good to know this issue was solved. In the latest version v0.7.0 either of those paths would work.
