### ISSUE TITLE
Docker run : "exec user process caused "exec format error"

### ISSUE THREAD

**Issue by bpgregson** [ipsingh06/seedsync#21]
I'm running [osmc](https://osmc.tv/about/) (Debian Stretch) on a [Vero 4K](https://osmc.tv/vero/) which has ARM architecture similar to Raspberry Pi.  
I successfully pulled the image from docker hub:
`osmc@osmc-turtle:~$ docker pull ipsingh06/seedsync`
then received an error when trying to run it:
```
osmc@osmc-turtle:~$ docker run -p 8800:8800 -v /mnt/media/PostProcessing/putio:/downloads ipsingh06/seedsync
standard_init_linux.go:178: exec user process caused "exec format error"
```
I'm aware that the x86_64 build is incompatible with ARM. Has an ARM build been compiled?
I performed the following steps to try to build the docker image locally.
```
osmc@osmc-turtle:~$ git clone https://github.com/ipsingh06/seedsync.git
osmc@osmc-turtle:~$ cd seedsync/
osmc@osmc-turtle:~/seedsync$ docker build -t ipsingh06/seedsync .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/osmc/seedsync/Dockerfile: no such file or directory
osmc@osmc-turtle:~$ ls seedsync/
LICENSE.txt  Makefile  README.md  doc  scripts  src
```
Since there isn't a Dockerfile in the seedsync directory, I'm unsure of how to proceed.

**Comment by ipsingh06** [comment]
Hi.

In the latest version v0.7.0 the docker image is now architecture independent. However, I'm pretty sure that the docker image still needs to be compiled on an ARM machine because the Ubuntu images that it depends on are architecture specific.

The build instructions for SeedSync are now available at https://github.com/ipsingh06/seedsync/blob/master/doc/DeveloperReadme.md
Let me know if this works for you.

**Comment by bpgregson** [comment]
thanks so much for your guide.  The documentation is great.  With it, I was able to make good progress.  I'm close.  I made it through your guide until the final step to `make` the .deb package.  The following are the steps I took, based on your guide.  At the end is the error output after running `make`.

It was necessary to first install `wheel` in order to install `docker-compose` via `pip`.
```
osmc@osmc-turtle:~$ sudo pip install wheel
osmc@osmc-turtle:~$ sudo pip install docker-compose
```
In my case, when installing the remaining dependencies I received the error `Package 'rar' has no installation candidate`.
instead, I installed `unrar-free`:
`osmc@osmc-turtle:~$ sudo apt-get install unrar-free`

The instructions for cloning the repo failed as written:
```
osmc@osmc-turtle:~$ git clone git@gitlab.com:ipsingh06/seedsync.git
Cloning into 'seedsync'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Rather, the following was successful:
```
osmc@osmc-turtle:~$ git clone https://github.com/ipsingh06/seedsync.git
Cloning into 'seedsync'...
remote: Enumerating objects: 6303, done.
remote: Total 6303 (delta 0), reused 0 (delta 0), pack-reused 6303
Receiving objects: 100% (6303/6303), 15.59 MiB | 5.47 MiB/s, done.
Resolving deltas: 100% (4359/4359), done.
```
It was necessary to set the location where the virtual environments live, the location of the development project directories, and the location of the script installed with this package, by editing `~/.bashrc`:
```
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
source /usr/local/bin/virtualenvwrapper.sh
```
before making the virtualenv:
`osmc@osmc-turtle:~/seedsync$ mkvirtualenv -p python3.5 seedsync`

In order to [setup the end-to-end node modules](https://github.com/ipsingh06/seedsync/blob/master/doc/DeveloperReadme.md#setup-end-to-end-tests-node-modules), it should be clarified that the `e2e` directory is located in `~/seedsync/src/e2e` instead of `~/seedsync/src/angular/src/e2e` (which doesn't exist).
```
osmc@osmc-turtle:~/seedsync/src/angular$ cd ../e2e/
osmc@osmc-turtle:~/seedsync/src/e2e$ npm install
```
For clarification, I changed to the `seedsync` root directory to build the package.
```
osmc@osmc-turtle:~/seedsync/src/e2e$ cd ~/seedsync/
osmc@osmc-turtle:~/seedsync$ make clean
````

**ERRORS START HERE:**
```
osmc@osmc-turtle:~/seedsync$ make
mkdir -p build
pyinstaller /home/osmc/seedsync/src/python/seedsync.py \
        -y \
        -p /home/osmc/seedsync/src/python \
        --distpath /home/osmc/seedsync/build/py-dist \
        --workpath /home/osmc/seedsync/build/py-work \
        --specpath /home/osmc/seedsync/build \
        --additional-hooks-dir /home/osmc/seedsync/src/pyinstaller_hooks/ \
        --name seedsync
946 INFO: PyInstaller: 3.3
947 INFO: Python: 3.5.3
950 INFO: Platform: Linux-3.14.29-134-osmc-aarch64-with-debian-9.6
951 INFO: wrote /home/osmc/seedsync/build/seedsync.spec
957 INFO: UPX is not available.
964 INFO: Extending PYTHONPATH with paths
['/home/osmc/seedsync/src',
 '/home/osmc/seedsync/src/python',
 '/home/osmc/seedsync/build']
964 INFO: checking Analysis
965 INFO: Building Analysis because out00-Analysis.toc is non existent
965 INFO: Initializing module dependency graph...
970 INFO: Initializing module graph hooks...
977 INFO: Analyzing base_library.zip ...
23357 INFO: running Analysis out00-Analysis.toc
23458 INFO: Caching module hooks...
23482 INFO: Analyzing /home/osmc/seedsync/src/python/seedsync.py
25055 INFO: Processing pre-find module path hook   distutils
25057 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.5/distutils/__init__.py'
36228 INFO: Processing pre-safe import module hook   six.moves
41861 INFO: Loading module hooks...
41862 INFO: Loading module hook "hook-sysconfig.py"...
41874 INFO: Loading module hook "hook-patoolib.py"...
42468 INFO: Loading module hook "hook-encodings.py"...
42800 INFO: Loading module hook "hook-xml.py"...
43168 INFO: Loading module hook "hook-paste.exceptions.reporter.py"...
43172 INFO: Loading module hook "hook-pkg_resources.py"...
44667 INFO: Processing pre-safe import module hook   win32com
46241 INFO: Loading module hook "hook-pydoc.py"...
46372 INFO: Looking for ctypes DLLs
46603 INFO: Analyzing run-time hooks ...
46638 INFO: Including run-time hook 'pyi_rth_pkgres.py'
46646 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
46735 INFO: Looking for dynamic libraries
47369 INFO: Looking for eggs
47370 INFO: Python library not in binary dependencies. Doing additional searching...
47416 INFO: Using Python library /usr/lib/arm-linux-gnueabihf/libpython3.5m.so.1.0
47450 INFO: Warnings written to /home/osmc/seedsync/build/py-work/seedsync/warnseedsync.txt
47839 INFO: Graph cross-reference written to /home/osmc/seedsync/build/py-work/seedsync/xref-seedsync.html
47958 INFO: checking PYZ
47958 INFO: Building PYZ because out00-PYZ.toc is non existent
47959 INFO: Building PYZ (ZlibArchive) /home/osmc/seedsync/build/py-work/seedsync/out00-PYZ.pyz
51703 INFO: Building PYZ (ZlibArchive) /home/osmc/seedsync/build/py-work/seedsync/out00-PYZ.pyz completed successfully.
51777 INFO: checking PKG
51777 INFO: Building PKG because out00-PKG.toc is non existent
51778 INFO: Building PKG (CArchive) out00-PKG.pkg
51865 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
51869 INFO: Bootloader /home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/bootloader/Linux-32bit/run
51870 INFO: checking EXE
51871 INFO: Building EXE because out00-EXE.toc is non existent
51871 INFO: Building EXE from out00-EXE.toc
51873 INFO: Appending archive to ELF section in EXE /home/osmc/seedsync/build/py-work/seedsync/seedsync
Traceback (most recent call last):
  File "/home/osmc/.virtualenvs/seedsync/bin/pyinstaller", line 10, in <module>
    sys.exit(run())
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/building/api.py", line 420, in __init__
    self.__postinit__()
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/home/osmc/.virtualenvs/seedsync/lib/python3.5/site-packages/PyInstaller/building/api.py", line 581, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy: Unable to recognise the format of the input file `/home/osmc/seedsync/build/py-work/seedsync/seedsync'

Makefile:14: recipe for target 'py' failed
make: *** [py] Error 1
```

**Comment by ipsingh06** [comment]
OK, you actually don't need to build the deb file since we only want the docker image for ARM. Unfortunately you do need to cross-compile scanfs for the remote seedbox architecture, which I will assume is x86-64.

For now, could you please try the following commands:
```bash
make py   # this will fail, that's fine
make scanfs  # this will fail too, that's fine
make ng
make artifacts
make docker
```
If this works then all we need to do is transplant the x86-64 version of scanfs before running `make docker`.
I will also look for an easier way to cross compile the docker image for ARM architectures.

**Comment by bpgregson** [comment]
Thanks again for your quick reply.

`make ng` was successful but the commands failed at `make artifacts`.
```
osmc@osmc-turtle:~/seedsync$ make py
mkdir -p build
pyinstaller /home/osmc/seedsync/src/python/seedsync.py \
        -y \
        -p /home/osmc/seedsync/src/python \
        --distpath /home/osmc/seedsync/build/py-dist \
        --workpath /home/osmc/seedsync/build/py-work \
        --specpath /home/osmc/seedsync/build \
        --additional-hooks-dir /home/osmc/seedsync/src/pyinstaller_hooks/ \
        --name seedsync
make: pyinstaller: Command not found
Makefile:14: recipe for target 'py' failed
make: *** [py] Error 127
osmc@osmc-turtle:~/seedsync$ make scanfs
mkdir -p build
pyinstaller /home/osmc/seedsync/src/python/scan_fs.py \
        -y \
        --onefile \
        -p /home/osmc/seedsync/src/python \
        --distpath /home/osmc/seedsync/build/scanfs-dist \
        --workpath /home/osmc/seedsync/build/scanfs-work \
        --specpath /home/osmc/seedsync/build \
        --name scanfs
make: pyinstaller: Command not found
Makefile:24: recipe for target 'scanfs' failed
make: *** [scanfs] Error 127
osmc@osmc-turtle:~/seedsync$ make ng
mkdir -p build
cd /home/osmc/seedsync/src/angular && \
ng build -prod --output-path /home/osmc/seedsync/build/ng-dist
Your global Angular CLI version (7.3.0) is greater than your local
version (1.3.2). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Date: 2019-02-05T02:39:36.818Z                                                  Hash: b66540b945d471c0c15d
Time: 163353ms
chunk {0} polyfills.01c11f55b6681530305a.bundle.js (polyfills) 68.6 kB {5} [initial] [rendered]
chunk {1} main.d2e24d6c34e05b476584.bundle.js (main) 223 kB {4} [initial] [rendered]
chunk {2} scripts.011a89ab56a31e3ca463.bundle.js (scripts) 165 kB {5} [initial] [rendered]
chunk {3} styles.7b312a4f6b5b17fd93a7.bundle.css (styles) 182 kB {5} [initial] [rendered]
chunk {4} vendor.213f9462f0070151a88e.bundle.js (vendor) 814 kB [initial] [rendered]
chunk {5} inline.cca0871609b97065e124.bundle.js (inline) 1.47 kB [entry] [rendered]
osmc@osmc-turtle:~/seedsync$ make artifacts
rm -rf /home/osmc/seedsync/build/artifacts
mkdir -p /home/osmc/seedsync/build/artifacts
cp -rf /home/osmc/seedsync/build/py-dist/seedsync/* /home/osmc/seedsync/build/artifacts/
cp: cannot stat '/home/osmc/seedsync/build/py-dist/seedsync/*': No such file or directory
Makefile:38: recipe for target 'artifacts' failed
make: *** [artifacts] Error 1
osmc@osmc-turtle:~/seedsync$
```

**Comment by bpgregson** [comment]
> `cp -rf /home/osmc/seedsync/build/py-dist/seedsync/* /home/osmc/seedsync/build/artifacts/ cp: cannot stat '/home/osmc/seedsync/build/py-dist/seedsync/*': No such file or directory`

In the `Makefile`, if I change the line
`cp -rf ${BUILDDIR}/py-dist/seedsync/* ${BUILDDIR}/artifacts/`
to
`cp -rf ${BUILDDIR}/py-work/seedsync/* ${BUILDDIR}/artifacts/`, the build proceeds.
```
osmc@osmc-turtle:~/seedsync$ nano Makefile
```
edit the following section as shown below (save and return to working directory):
```
artifacts:
        rm -rf ${BUILDDIR}/artifacts
        mkdir -p ${BUILDDIR}/artifacts
#       cp -rf ${BUILDDIR}/py-dist/seedsync/* ${BUILDDIR}/artifacts/
        cp -rf ${BUILDDIR}/py-work/seedsync/* ${BUILDDIR}/artifacts/
        cp -rf ${BUILDDIR}/ng-dist ${BUILDDIR}/artifacts/html
        cp -f ${BUILDDIR}/scanfs-dist/scanfs ${BUILDDIR}/artifacts/
        cat ${SOURCEDIR}/debian/changelog \
        | grep -m1 -o "seedsync \(([0-9\.\-]*)\) stable" \
        | grep -o [0-9\.\-]* \
        | sed 's/\-/\./' \
        > ${BUILDDIR}/artifacts/VERSION
```
However, `make docker` then fails.  It looks like it has something to do with installation of the package `rar` dependency.  I'm not sure what script to edit to try to work through that.  Thoughts?
```
osmc@osmc-turtle:~/seedsync$ make docker
rm -rf /home/osmc/seedsync/build/docker
mkdir -p /home/osmc/seedsync/build/docker
cp -rf /home/osmc/seedsync/src/python /home/osmc/seedsync/build/docker/python
cp -rf /home/osmc/seedsync/build/artifacts/html /home/osmc/seedsync/build/docker/html
cp -rf /home/osmc/seedsync/build/artifacts/scanfs /home/osmc/seedsync/build/docker/scanfs
cp -rf /home/osmc/seedsync/build/artifacts/VERSION /home/osmc/seedsync/build/docker/ARTIFACTS_VERSION
cp -rf /home/osmc/seedsync/src/docker/release/. /home/osmc/seedsync/build/docker/
/home/osmc/seedsync/build/docker/build.sh
Sending build context to Docker daemon  2.897MB
Step 1/16 : FROM ubuntu:16.04
 ---> 8593318db04f
Step 2/16 : RUN apt-get update && apt-get install -y     libssl-dev     lftp     openssh-client     rar     unrar     p7zip     python3-pip
 ---> Running in 5c941cfab2df
Get:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease [247 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [109 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports xenial-backports InRelease [107 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [109 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports xenial/main armhf Packages [1486 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports xenial/restricted armhf Packages [8491 B]
Get:7 http://ports.ubuntu.com/ubuntu-ports xenial/universe armhf Packages [9531 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports xenial/multiverse armhf Packages [149 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf Packages [938 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports xenial-updates/restricted armhf Packages [8475 B]
Get:11 http://ports.ubuntu.com/ubuntu-ports xenial-updates/universe armhf Packages [828 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports xenial-updates/multiverse armhf Packages [13.4 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports xenial-backports/main armhf Packages [7936 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports xenial-backports/universe armhf Packages [8151 B]
Get:15 http://ports.ubuntu.com/ubuntu-ports xenial-security/main armhf Packages [577 kB]
Get:16 http://ports.ubuntu.com/ubuntu-ports xenial-security/restricted armhf Packages [8480 B]
Get:17 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe armhf Packages [457 kB]
Get:18 http://ports.ubuntu.com/ubuntu-ports xenial-security/multiverse armhf Packages [3015 B]
Fetched 14.6 MB in 6s (2403 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package rar is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'rar' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y     libssl-dev     lftp     openssh-client     rar     unrar     p7zip     python3-pip' returned a non-zero code: 100
Makefile:58: recipe for target 'docker' failed
make: *** [docker] Error 100
```

**Comment by ipsingh06** [comment]
That's great progress. A couple of things:

1. You're still running the release docker ipsingh06/seedsync. You need to run the one you compiled: seedsync:0.7.0.

2. Your docker image is missing the scanfs executable. You will need to grab it from the official release and place it in `build/docker/scanfs` and run `make docker` again. In the official docker image it is located at `/app/scanfs`

**Comment by bpgregson** [comment]
With [dependencies already installed](https://github.com/ipsingh06/seedsync/blob/master/doc/DeveloperReadme.md#install-dependencies) and [code already fetched](https://github.com/ipsingh06/seedsync/blob/master/doc/DeveloperReadme.md#fetch-code), I basically started again from scratch, based on the steps from our previous posts.  The following are the commands I ran, some of it redundant or unnecessary, for a successful build.
```
osmc@osmc-turtle:~/seedsync$ make clean
osmc@osmc-turtle:~/seedsync$ mkvirtualenv -p python3.5 seedsync
osmc@osmc-turtle:~/seedsync$ pip install -r src/python/requirements.txt
osmc@osmc-turtle:~/seedsync$ cd src/angular/
osmc@osmc-turtle:~/seedsync/src/angular$ npm install
osmc@osmc-turtle:~/seedsync/src/angular$ cd ../e2e/
osmc@osmc-turtle:~/seedsync/src/e2e$ npm install
osmc@osmc-turtle:~/seedsync/src/e2e$ cd ~/seedsync/
osmc@osmc-turtle:~/seedsync$ make clean
osmc@osmc-turtle:~/seedsync$ make
osmc@osmc-turtle:~/seedsync$ make py    # fails as expected
osmc@osmc-turtle:~/seedsync$ make scanfs    # fails as expected
osmc@osmc-turtle:~/seedsync$ make ng
osmc@osmc-turtle:~/seedsync$ make artifacts    # using [modified Makefile](https://github.com/ipsingh06/seedsync/issues/21#issuecomment-460501147)
osmc@osmc-turtle:~/seedsync$ mkdir tmp
osmc@osmc-turtle:~/seedsync$ docker ps -l
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                     PORTS               NAMES
b0480b5e7034        ipsingh06/seedsync   "python3.5 /app/py..."   6 seconds ago       Exited (1) 4 seconds ago                       nifty_rosalind
osmc@osmc-turtle:~/seedsync$ docker cp nifty_rosalind:/app /home/osmc/seedsync/tmp
osmc@osmc-turtle:~/seedsync$ ls tmp/app/scanfs
tmp/app/scanfs
osmc@osmc-turtle:~/seedsync$ mkdir build/docker
osmc@osmc-turtle:~/seedsync$ cp tmp/app/scanfs build/docker/scanfs
osmc@osmc-turtle:~/seedsync$ make docker
...
Successfully built 5bedca81851b
Successfully tagged seedsync:0.7.0
Finished building docker image seedsync:0.7.0
osmc@osmc-turtle:~/seedsync$ docker image ls
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
seedsync                     0.7.0               5bedca81851b        23 hours ago        431MB
osmc@osmc-turtle:~/seedsync$ mkdir ~/.seedsync
osmc@osmc-turtle:~/seedsync$ mkdir ~/.seedsync/config
osmc@osmc-turtle:~/seedsync$ docker run -p 8800:8800 -v /mnt/media/PostProcessing/seedsync/:/downloads -v /home/osmc/.seedsync/config/:/config seedsync:0.7.0
```
The output generates the following:
```
2019-02-06 03:00:49,735 - INFO - seedsync (MainProcess/MainThread) - Debug mode is disabled.
2019-02-06 03:00:49,738 - INFO - seedsync (MainProcess/MainThread) - Starting seedsync
2019-02-06 03:00:50,605 - INFO - seedsync.WebApp (MainProcess/MainThread) - Html path set to: /app/html
2019-02-06 03:00:50,666 - ERROR - seedsync (MainProcess/MainThread) - Config is incomplete
```
and then I am SUCCESSFULLY able to access the dashboard through port 8800.

**Comment by bpgregson** [comment]
I'm going to close the issue because I was able to get it installed and functioning.  But as good practice we may want to revisit the modifications to Makefile and Dockerfile referenced above.  Also, I'll be happy to help with cross-compiling for ARM, although I don't have much experience with the workflow.

**Comment by SJ50** [comment]
Is it possible to put all this in docker file, I do not want to repeat all these steps for every new release.

**Comment by arthursoares** [comment]
I'm also interested in this.

**Comment by ipsingh06** [comment]
Guys I've created an experimental docker image for armv7 and armv8 architectures. Please give it a try. Instructions and discussion here: https://github.com/ipsingh06/seedsync/issues/57#issuecomment-672409738
