### ISSUE TITLE
Permission error when installing

### ISSUE THREAD

**Issue by Sykeya** [ipsingh06/seedsync#33]
Windows 10 Home
Docker toolkit
hello-world app ok

`$ docker run \
>     -p 8800:8800 \
>     -v /d/sync:/downloads \
>     -v /d/syncconfig:/config \
>     ipsingh06/seedsync
Traceback (most recent call last):
  File "/app/python/seedsync.py", line 376, in <module>
    seedsync = Seedsync()
  File "/app/python/seedsync.py", line 59, in __init__
    config.to_file(self.config_path)
  File "/app/python/common/persist.py", line 53, in to_file
    with open(file_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/config/settings.cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/python/seedsync.py", line 384, in <module>
    Seedsync.logger.exception("Caught exception")
AttributeError: 'NoneType' object has no attribute 'exception'`

**Comment by ipsingh06** [comment]
Please try the latest version (v0.7.1). I updated the Docker image to (hopefully) address this issue.
