### ISSUE TITLE
An error occurred while installing script [...]

### ISSUE THREAD

**Issue by haboutnnah** [ipsingh06/seedsync#37]
OS: Windows 10

Command:

```
docker run -p 8800:8800 -v /l/_MEDIA/TorrentOut:/downloads  -v /c/Users/Hannah/Git/Docker/seedsync/config:/config ipsingh06/seedsync
```

Debug Logs:
```
2019/04/24 09:59:52 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2019/04/24 10:00:12 - DEBUG - seedsync - Persisting states to file
2019/04/24 10:00:23 - DEBUG - seedsync.ControllerJob - Thread ControllerJob started
2019/04/24 10:00:23 - DEBUG - seedsync.ControllerJob - Calling setup for ControllerJob
2019/04/24 10:00:23 - DEBUG - seedsync.Controller - Starting controller
2019/04/24 10:00:23 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2019/04/24 10:00:23 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2019/04/24 10:00:23 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2019/04/24 10:00:24 - DEBUG - seedsync.Controller.MPLogger - Started listener thread
2019/04/24 10:00:24 - DEBUG - seedsync.ControllerJob - Finished setup for ControllerJob
2019/04/24 10:00:24 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 523, in __propagate_exceptions
self.__local_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/local_scanner.py", line 31, in scan
raise AppError(Localization.Error.LOCAL_SERVER_SCAN)
common.error.AppError: An error occurred while scanning the local system.
2019/04/24 10:00:24 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob
2019/04/24 10:00:24 - DEBUG - seedsync.Controller - Exiting controller
2019/04/24 10:00:23 - DEBUG - ActiveScanner - Started process
2019/04/24 10:00:23 - DEBUG - RemoteScanner - Started process
2019/04/24 10:00:23 - DEBUG - RemoteScanner - Running a scan
2019/04/24 10:00:23 - DEBUG - LocalScanner - Started process
2019/04/24 10:00:24 - DEBUG - LocalScanner - Running a scan
2019/04/24 10:00:24 - ERROR - LocalScanner.LocalScanner - Caught SystemScannerError
Traceback (most recent call last):
File "/app/python/controller/scan/local_scanner.py", line 28, in scan
result = self.__scanner.scan()
File "/app/python/system/scanner.py", line 81, in scan
raise SystemScannerError("Path does not exist: {}".format(self.path_to_scan))
system.scanner.SystemScannerError: Path does not exist: /c/Users/Hannah/Downloads
2019/04/24 10:00:24 - DEBUG - LocalScanner - Process caught an exception
2019/04/24 10:00:24 - DEBUG - RemoteScanner.RemoteScanner - Local scanfs md5sum = 598ad3ef4659f41c8749d22c72f7a0fe
2019/04/24 10:00:24 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no user02@62.210.75.6 "echo '598ad3ef4659f41c8749d22c72f7a0fe /tmp/scanfs' | md5sum -c --quiet"
2019/04/24 10:00:24 - DEBUG - ExtractProcess - Started process
2019/04/24 10:00:24 - DEBUG - ExtractDispatch - Started worker thread
2019/04/24 10:00:24 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 523, in __propagate_exceptions
self.__local_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/local_scanner.py", line 31, in scan
raise AppError(Localization.Error.LOCAL_SERVER_SCAN)
common.error.AppError: An error occurred while scanning the local system.
2019/04/24 10:00:24 - DEBUG - ActiveScanner - Process received terminate flag
2019/04/24 10:00:24 - DEBUG - ActiveScanner - Exiting process
2019/04/24 10:00:26 - DEBUG - ExtractProcess - Process received terminate flag
2019/04/24 10:00:26 - DEBUG - seedsync.Controller.MPLogger - Stopped listener thread
2019/04/24 10:00:26 - INFO - seedsync.Controller - Exited controller
2019/04/24 10:00:26 - DEBUG - seedsync.ControllerJob - Finished cleanup for ControllerJob
2019/04/24 10:00:26 - DEBUG - seedsync.ControllerJob - Thread ControllerJob stopped
2019/04/24 10:00:26 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
```

**Comment by haboutnnah** [comment]
Progress. Tried a different server and now it's just perpetually waiting for remote.

**Comment by haboutnnah** [comment]
```2019/04/24 11:22:16 - INFO - RemoteScanner.RemoteScanner - Installing local:/app/scanfs to remote:/home25/haboutnnah/bin/seedsync/scanfs
2019/04/24 11:22:20 - ERROR - RemoteScanner.RemoteScanner - Caught scp exception
Traceback (most recent call last):
File "/app/python/controller/scan/remote_scanner.py", line 115, in _install_scanfs
remote_path=self.__remote_path_to_scan_script)
File "/app/python/ssh/sshcp.py", line 169, in copy
args=" ".join(args)
File "/app/python/ssh/sshcp.py", line 109, in __run_command
raise SshcpError(sp.before.decode())
ssh.sshcp.SshcpError: 
scp: /home25/haboutnnah/bin/seedsync/scanfs: No such file or directory
2019/04/24 11:22:20 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 524, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 57, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 118, in _install_scanfs
raise AppError(Localization.Error.REMOTE_SERVER_INSTALL)
common.error.AppError: An error occurred while installing scanner script to remote server.
2019/04/24 11:22:20 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 524, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 57, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 118, in _install_scanfs
raise AppError(Localization.Error.REMOTE_SERVER_INSTALL)
common.error.AppError: An error occurred while installing scanner script to remote server.
2019/04/24 11:22:22 - INFO - seedsync.Controller - Exited controller
```

**Comment by ipsingh06** [comment]
Please try the latest version and see if you still get this error.
