### ISSUE TITLE
Ubuntu 18.04 - An Error occurred while scanning the local system

### ISSUE THREAD

**Issue by stakeout55** [ipsingh06/seedsync#48]
Hi there, no matter what I try... I keep getting this error: **An Error occurred while scanning the local system**  in a red banner at the top of my screen. Any thoughts? Thanks!

2020/02/09 18:21:02 - INFO - seedsync.ServerActionHandler - Received a restart action
2020/02/09 18:21:03 - INFO - seedsync - Exiting Seedsync
2020/02/09 18:21:05 - ERROR - LocalScanner.LocalScanner - Caught SystemScannerError
Traceback (most recent call last):
File "/app/python/controller/scan/local_scanner.py", line 28, in scan
result = self.__scanner.scan()
File "/app/python/system/scanner.py", line 81, in scan
raise SystemScannerError("Path does not exist: {}".format(self.path_to_scan))
system.scanner.SystemScannerError: Path does not exist: /home/server/Downloads/
2020/02/09 18:21:05 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 523, in __propagate_exceptions
self.__local_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/local_scanner.py", line 31, in scan
raise AppError(Localization.Error.LOCAL_SERVER_SCAN)
common.error.AppError: An error occurred while scanning the local system.
2020/02/09 18:21:06 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 162, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 523, in __propagate_exceptions
self.__local_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/local_scanner.py", line 31, in scan
raise AppError(Localization.Error.LOCAL_SERVER_SCAN)
common.error.AppError: An error occurred while scanning the local system.
2020/02/09 18:21:07 - INFO - seedsync.Controller - Exited controller

**Comment by Elmlea** [comment]
Same issue running via docker on MacOS.  It always seems to fail on my local path; same as your line

system.scanner.SystemScannerError: Path does not exist: /home/server/Downloads/

**Comment by jackneil** [comment]
you should ONLY put '/downloads' into where it asks for 'local directory' on the settings webpage. This is mapped by your docker call when you enter something like 
docker ... -v /mnt/media/downloads/:/downloads

so by entering '/downloads' into the local directory textbox in the web GUI it is automatically mapped to the /mnt/media/downloads folder locally.

**Comment by ipsingh06** [comment]
@stakeout55 were you able to figure this out? As Jack mentioned, if using the Docker image and the instructions provided, always leave the local path as `/downloads` in settings.

**Comment by stakeout55** [comment]
I was not unfortunately, I gave up on seedsync actually
