### ISSUE TITLE
Unpickling error: unpickling stack underflow 

### ISSUE THREAD

**Issue by proximix** [ipsingh06/seedsync#54]
I started receiving the error after the update.  Any suggestions.  It looks like it can't set the locale c.utf-8 on my remote server if I am reading that right?

ERROR - RemoteScanner.RemoteScanner - Unpickling error: unpickling stack underflow b'bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
2020/06/01 17:38:40 - DEBUG - RemoteScanner - Process caught an exception
2020/06/01 17:38:40 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 524, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 71, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 83, in scan
raise AppError(Localization.Error.REMOTE_SERVER_SCAN)
common.error.AppError: An error occurred while scanning the remote server.

**Comment by proximix** [comment]
Figured it out, ended up setting my ENV in my docker-compose file to below:

- LC_ALL=en_US.UTF-8
