### ISSUE TITLE
Scanfs permissions error

### ISSUE THREAD

**Issue by quadcom** [ipsingh06/seedsync#61]
Started up with Seedhost. They must lock things down which is stopping the remote scanner from installing.

2020/06/22 12:52:36 - ERROR - RemoteScanner.RemoteScanner - Caught scp exception Traceback (most recent call last): File "/app/python/controller/scan/remote_scanner.py", line 117, in _install_scanfs remote_path=self.__remote_path_to_scan_script) File "/app/python/ssh/sshcp.py", line 198, in copy args=" ".join(args) File "/app/python/ssh/sshcp.py", line 138, in __run_command raise SshcpError(sp.before.decode().strip()) ssh.sshcp.SshcpError: scp: /tmp/scanfs: Permission denied
2020/06/22 12:52:36 - DEBUG - RemoteScanner - Process caught an exception
2020/06/22 12:52:37 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob

Is there any way to work around this in the event the provider won't adjust permissions?

**Comment by quadcom** [comment]
Nevermind, I'm a goof.

Changed the script path duh.
