### ISSUE TITLE
 An error occurred while installing scanner script to remote server: '/bin/bash: No such file or directory'.

### ISSUE THREAD

**Issue by Drizztfire** [ipsingh06/seedsync#73]
Running under Docker Ubuntu server

```
2020/10/31 12:49:29 - ERROR - seedsync - Caught exception
Traceback (most recent call last):
File "/app/python/seedsync.py", line 164, in run
controller_job.propagate_exception()
File "/app/python/common/job.py", line 77, in propagate_exception
raise exc_info[1].with_traceback(exc_info[2])
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 526, in __propagate_exceptions
self.__remote_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/remote_scanner.py", line 51, in scan
self._install_scanfs()
File "/app/python/controller/scan/remote_scanner.py", line 100, in _install_scanfs
recoverable=False
controller.scan.scanner_process.ScannerError: An error occurred while installing scanner script to remote server: '/bin/bash: No such file or directory'.
2020/10/31 12:49:31 - INFO - seedsync.Controller - Exited controller
```

**Comment by ipsingh06** [comment]
What operating system do you have installed on the remote server? SeedSync assumes that the remote server has Bash installed, but I think I should relax that assumption.

**Comment by ak4ge** [comment]
Just had this same issues, what fixed it for me was adding a backslash after the final dir in Server Script Path, e.g;

"/home/user/files/downloads" to  "/home/user/files/downloads/"

I'd also wager it shouldn't be going in bin/bash but the directory you are looking to download from.
