### ISSUE TITLE
SeedSync - Lost Connection to Server

### ISSUE THREAD

**Issue by jeffward01** [ipsingh06/seedsync#75]
Hey all,

Just installed this on my UnRaid server via Docker.

I can't get past the setup step, as soon as I begin to enter in details, or after I enter in details and after X amount of time I get the error:
`Lost Connection to SeedSync`

Here is my Log:
https://pastebin.com/eCP2qz4G

See Images:
https://ibb.co/W0hCv8B
https://ibb.co/nCqh8HB

---

Does anyone know what is going on?

**Comment by quadcom** [comment]
I don't see a user/group ID defined in the vars.

**Comment by jeffward01** [comment]
> I don't see a user/group ID defined in the vars.

Is this it? See highlights: https://ibb.co/kS28R5r

I followed these directions: https://github.com/ipsingh06/seedsync/issues/25#issuecomment-466546009

**Comment by quadcom** [comment]
sorry, see them there now. Are you sure that this userID and groupID have permission to read/write to the mapped dir's?

**Comment by quadcom** [comment]
I run SS in a docker on a Synology NAS. I can't use the UI to spin up the new container. I have to run a SSH command to get it working. Perhaps it is the same issue with the UNRAID setup?

`sudo docker run --name SeedSync -p 8802:8800 -v /volume3/Sync/Seedbox/z-config:/config -v /volume3/Sync/Seedbox/1-Incoming:/incoming --user 1039:65539 ipsingh06/seedsync:latest
`

**Comment by jeffward01** [comment]
yea I am pretty sure they have read/write access, its the same user / group ID's as my other dockers.  See Plex config here: https://ibb.co/1vqJTZv

> I run SS in a docker on a Synology NAS. I can't use the UI to spin up the new container. I have to run a SSH command to get it working. Perhaps it is the same issue with the UNRAID setup?
> 
> `sudo docker run --name SeedSync -p 8802:8800 -v /volume3/Sync/Seedbox/z-config:/config -v /volume3/Sync/Seedbox/1-Incoming:/incoming --user 1039:65539 ipsingh06/seedsync:latest `

I think your right about this, the error occurs and it crashes after I input my config (server name, username, password, download directory, remote directory), which tells me it tries to connect then fail.

From this post here: https://github.com/ipsingh06/seedsync/issues/25#issuecomment-609228328

The user says: 

> I didn’t get a chance to thank you for your instructions . They worked out great . I managed to set it up as a docker run prior to your comment, but I didn’t know you could create templates that would rebuild on shutdown. **The only thing I had to do in addition to following your instructions was to exec into the docker and setup the no password ssh session with my server** . This worked out great, and it is by far the fastest way I’ve found to get stuff from my box

I think thats what I need to do like you said, ahh.. more learning haha. I am savvy, but docker is a bit new to me.  I used Filezilla & SmartFTP and both of them are very slow, so I wanted to use this instead

**Comment by quadcom** [comment]
Night and day difference when you get this running. I have GIG internet and I'll get about 40MB/s easy.

**Comment by quadcom** [comment]
Try to config with a simple sFTP uname / password before you try going the SSSH keys route.

I've never gotten keys to work (haven't tried hard enough maybe).

At least get it connecting to the server first. 

TO me this sounds like SS can't save the config which would point to permissions problems not being able to write to the dir.

**Comment by jeffward01** [comment]
> Night and day difference when you get this running. I have GIG internet and I'll get about 40MB/s easy.

Thats crazy... I have almost 120 MB/s down that I pay for for Verizon, yet in Filezilla I only get 12MB/s tops. Usually much less.  In SmartFTP I got around 2MB/s... This is why I am burning hours on this haha.

Nice job getting it working!

I will keep trying this, I think its got to be with FTP or some docker thing like you said.  I'll keep trying on it and report back here!

Thanks for the lightening fast replies! It has to be a new record :)

**Comment by quadcom** [comment]
Can you startup SS, go to settings and leave everything as it is except for log level at the bottom right. Can you turn on Enable Debug?

Hit restart and see if it saves the settings. If it does the logs will have more details inside of SS on the logs tab. Paste those. 

I looked at the logs you posted. They look like Docker logs rather than SS logs. I don't see what problem SS is having.

**Comment by ipsingh06** [comment]
@jeffward01 Could you please post the logs and the settings page from within SeedSync interface? Also remember to enable debug logging in the settings page.

**Comment by jkexbx** [comment]
I also have this issue. I setup my docker with the options from this issue https://github.com/ipsingh06/seedsync/issues/25#issuecomment-466546009 and was able to connect fine and put in my config. I restarted the container after adding the config and now I can't get it to start and just get Lost connection to the SeedSync service.

I can confirm that it was able to write my settings to the config file. Here is the error I get from the logging

> 2021/01/05 18:38:11 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:38:12 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:38:14 - ERROR - seedsync - Config is incomplete
2021/01/05 18:38:14 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:38:14 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:38:14 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:38:16 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:38:23 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:38:43 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:38:43 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:38:46 - ERROR - seedsync - Config is incomplete
2021/01/05 18:38:46 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:38:46 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:38:46 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:38:47 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:38:48 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:01 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:39:02 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:39:04 - ERROR - seedsync - Config is incomplete
2021/01/05 18:39:04 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:39:04 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:39:04 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:39:06 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:06 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:15 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:39:16 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:39:17 - ERROR - seedsync - Config is incomplete
2021/01/05 18:39:17 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:39:17 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:39:17 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:39:19 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:19 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:36 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:39:36 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:39:39 - ERROR - seedsync - Config is incomplete
2021/01/05 18:39:39 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:39:39 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:39:39 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:39:40 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:39:40 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:40:09 - DEBUG - seedsync - Persisting states to file
2021/01/05 18:40:33 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:40:39 - DEBUG - seedsync - Persisting states to file
2021/01/05 18:40:39 - DEBUG - seedsync.WebApp - Stream connection stopped by client
2021/01/05 18:40:39 - DEBUG - seedsync.Controller.Model - LftpModel: Removing a listener
2021/01/05 18:40:54 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:40:54 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:40:57 - ERROR - seedsync - Config is incomplete
2021/01/05 18:40:57 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:40:57 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:40:57 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:40:58 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:40:58 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:41:11 - INFO - seedsync.ServerActionHandler - Received a restart action
2021/01/05 18:41:11 - INFO - seedsync - Exiting Seedsync
2021/01/05 18:41:12 - DEBUG - seedsync.ControllerJob - Thread ControllerJob started
2021/01/05 18:41:12 - DEBUG - seedsync.WebAppJob - Thread WebAppJob started
2021/01/05 18:41:12 - DEBUG - seedsync.WebAppJob - Calling setup for WebAppJob
2021/01/05 18:41:12 - DEBUG - seedsync.ControllerJob - Calling setup for ControllerJob
2021/01/05 18:41:12 - DEBUG - seedsync.WebAppJob - Finished setup for WebAppJob
2021/01/05 18:41:12 - DEBUG - seedsync.Controller - Starting controller
2021/01/05 18:41:12 - DEBUG - seedsync.Controller.MPLogger - Started listener thread
2021/01/05 18:41:12 - DEBUG - ActiveScanner - Started process
2021/01/05 18:41:12 - DEBUG - ExtractProcess - Started process
2021/01/05 18:41:12 - DEBUG - seedsync.ControllerJob - Finished setup for ControllerJob
2021/01/05 18:41:12 - DEBUG - ExtractDispatch - Started worker thread
2021/01/05 18:41:12 - DEBUG - LocalScanner - Started process
2021/01/05 18:41:12 - DEBUG - LocalScanner - Running a scan
2021/01/05 18:41:12 - DEBUG - RemoteScanner - Started process
2021/01/05 18:41:12 - DEBUG - RemoteScanner - Running a scan
2021/01/05 18:41:12 - DEBUG - RemoteScanner.RemoteScanner - Local scanfs md5sum = e9b7600451a779ef32c2dc00f018d204
2021/01/05 18:41:12 - DEBUG - RemoteScanner.RemoteScanner.Sshcp - Command: ssh -p 15 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=error -o PubkeyAuthentication=no xboxftp@192.168.0.9 "md5sum /tmp/scanfs | awk '{print $1}' || echo"
2021/01/05 18:41:13 - DEBUG - LocalScanner - Process caught an exception
2021/01/05 18:41:14 - ERROR - seedsync.ControllerJob - Caught exception in job ControllerJob
Traceback (most recent call last):
File "/app/python/common/job.py", line 44, in run
self.execute()
File "/app/python/controller/controller_job.py", line 29, in execute
self.__controller.process()
File "/app/python/controller/controller.py", line 199, in process
self.__propagate_exceptions()
File "/app/python/controller/controller.py", line 525, in __propagate_exceptions
self.__local_scan_process.propagate_exception()
File "/app/python/common/app_process.py", line 124, in propagate_exception
raise exc.re_raise()
File "/app/python/common/app_process.py", line 30, in re_raise
raise self.ee.with_traceback(self.tb)
File "/app/python/common/app_process.py", line 87, in run
self.run_loop()
File "/app/python/controller/scan/scanner_process.py", line 90, in run_loop
files = self.__scanner.scan()
File "/app/python/controller/scan/local_scanner.py", line 28, in scan
result = self.__scanner.scan()
File "/app/python/system/scanner.py", line 84, in scan
return self.__create_children(self.path_to_scan)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 128, in __create_system_file
sub_children = self.__create_children(entry.path)
File "/app/python/system/scanner.py", line 187, in __create_children
sys_file = self.__create_system_file(entry)
File "/app/python/system/scanner.py", line 127, in __create_system_file
if entry.is_dir():
OSError: [Errno 40] Too many levels of symbolic links: '/dev/fd/123/dev/fd/123/dev/fd/123/dev/fd/123/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/fd/28/dev/stderr'
2021/01/05 18:41:14 - DEBUG - seedsync.ControllerJob - Calling cleanup for ControllerJob
2021/01/05 18:41:14 - DEBUG - seedsync.Controller - Exiting controller
2021/01/05 18:41:14 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:41:14 - DEBUG - seedsync.Controller.Model - LftpModel: Adding a listener
2021/01/05 18:41:15 - INFO - seedsync - Exiting Seedsync

**Comment by ipsingh06** [comment]
@jkexbx Could you please post your Seedsync config and your docker config? From the logs it looks like Seedsync is being pointed to a local directory that it shouldn't be pointed to.

**Comment by jkexbx** [comment]
I'm trying to sync files from a local ftp server to my unraid array.

Seedsync Config:
> [General]
debug = True
verbose = False
[Lftp]
remote_address = 192.168.0.9
remote_username = xboxftp
remote_password = ****
remote_port = 15
remote_path = /
local_path = /
remote_path_to_scan_script = /tmp
use_ssh_key = False
num_max_parallel_downloads = 2
num_max_parallel_files_per_download = 4
num_max_connections_per_root_file = 4
num_max_connections_per_dir_file = 4
num_max_total_connections = 16
use_temp_file = False
[Controller]
interval_ms_remote_scan = 30000
interval_ms_local_scan = 10000
interval_ms_downloading_scan = 1000
extract_path = /tmp
use_local_path_as_extract_path = True
[Web]
port = 8800
[AutoQueue]
enabled = True
patterns_only = False
auto_extract = True

Docker Config:
>-Downloads Path
Local: /mnt/user/X360/
Container: /downloads
-Config Path
Local: /mnt/user/appdata/seedsync
Container: /config
-Main Port
Host: 8800
Container: 8800
-Process User ID
Key: PUID
Value: 99
-Process Group ID
Key: PGID
Value: 100
-File Mode Creation Mask
Key: UMASK
Value: 000

Thanks for taking a look at it!

**Comment by quadcom** [comment]
I suspect this is your problem. Unless the ftp server supports SFTP is not going to work.

SS uses SSH to transfer using LFTP.

I may be wrong in my understanding here but I suspect this is the issue.

**Comment by jkexbx** [comment]
That's probably part of it. The ftp I'm trying to sync only supports active mode and I'm guess you also don't support that. I'm running through all the options trying to find a way to automatically sync an old ftp server (rclone also doesn't support active mode)

Thanks for the help! I will continue looking at other applications.

**Comment by ipsingh06** [comment]
@jkexbx It's likely to do with your `local_path` being set to the root directory. You should not be changing the local path if using the docker container.
